name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies for backend
        working-directory: backend
        run: |
          npm ci

      - name: Install dependencies for frontend
        working-directory: frontend
        run: |
          npm ci

      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps
      
      - name: Run backend tests
        working-directory: backend
        run: |
          npm test

      - name: Run Playwright tests
        working-directory: frontend
        run: npx playwright test

      - name: Upload Playwright test results if failed
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results
          path: frontend/test-results/
